### PR TITLE
Create SOS extensions for GeoNode MapStore client

### PR DESCRIPTION
**Pull request by DavidQuartz**
SOS catalogue

And Custom GFI viewer extensions

ref

### CODE REVIEW

**Comment by giohappy** [comment]
@DavidQuartz can you please put the close button inside the top bar? This way we gain some vertical space for the iframe.

**Comment by DavidQuartz** [comment]
> @DavidQuartz can you please put the close button inside the top bar? This way we gain some vertical space for the iframe.

How's this @giohappy ?

Screenshot 2022-06-15 at 09 25 59

**Comment by giohappy** [comment]
can we make the window title configurable? "Feature of Interests" is ok as a default, but it could be useful to let them call it as they prefer.

**Comment by DavidQuartz** [comment]
> can we make the window title configurable? "Feature of Interests" is ok as a default, but it could be useful to let them call it as they prefer.

@giohappy we can make it customizable, however, without translations

**Comment by giohappy** [comment]
no need translations. If they set a custom title it will be a static label.

**Comment by giohappy** [comment]
As agreed @DavidQuartz let's try to fix the resize behaviour. The end user shouldn't have to go back to the resize handle to stop resizing.

As a reference the behaviour implemented by [react-rnd](https://github.com/bokuweb/react-rnd/).
Example: https://codesandbox.io/s/xpm699v4lp?file=/src/app.js:1510-1513

Finally, please add a README inside the plugin folder explaining how to configure the iframe and the other options.

**Comment by DavidQuartz** [comment]
@giohappy
sos

**Review by giohappy — APPROVED** [review]

**Pull request merged**
